# Generated by Django 3.2.16 on 2024-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240423_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время публикации'),
        ),
        migrations.AddField(
            model_name='location',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время публикации'),
        ),
    ]
