# Generated by Django 3.2.16 on 2024-04-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240423_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='pub_date',
        ),
    ]
